source 'https://github.com/CocoaPods/Specs.git'

target 'NMessengerController', :exclusive => true do
  pod "NMessengerController", :path => "../"
  pod "NTextView", :git => "https://github.com/naithar/NTextView.git"
end

target 'Tests', :exclusive => true do
  pod "NMessengerController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
